[package]
edition = "2021"
name = "check"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.5.1", features = ["derive"]}
colored = "2.1.0"
indicatif = "0.17.8"
regex = "1.10.3"
which = "6.0.0"
