parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - prettier
plugins:
  - "@typescript-eslint"
  - only-warn
env:
  browser: true
  es2021: true
